import type { KnowledgeDocument } from './fleet.types';

/**
 * Synthetic standard operating procedures. Each document is written as several
 * paragraphs so the recursive splitter produces genuine multi-chunk documents
 * and retrieval has to select a passage rather than a whole file.
 */
export const KNOWLEDGE_DOCUMENTS: readonly KnowledgeDocument[] = [
  {
    id: 'KB-SAF-001',
    title: 'Brake Overheat Emergency Procedure',
    section: 'Immediate response and release criteria',
    category: 'Safety',
    content: [
      'Scope. This procedure applies to any brake, hub, or wheel-end temperature alert above 200°C reported by trailer axle sensors, tractor telemetry, or driver observation. It covers the immediate stop, the exclusion zone, the technician inspection, and the criteria for returning the vehicle to service.',
      'Immediate response. The driver must stop at the nearest safe location and avoid applying the parking brake to the affected wheel where road gradient and load allow. Establish a 15-metre exclusion zone on the affected side and keep all personnel clear of the wheel and rim. Notify dispatch with the vehicle ID, axle position, recorded temperature, and location. Never apply water, foam, or any coolant to an overheated wheel end: rapid cooling can fracture the drum or rotor and can cause a pressurised tyre explosion. Allow the assembly to cool by ambient air only.',
      'Escalation. If flame, visible smoke, or an audible air leak is present, treat the event as a fire risk. Evacuate to at least 50 metres upwind, call emergency services, and inform the fleet safety duty manager. Only trained personnel may attempt to use an extinguisher, and only when it is safe to do so. Dispatch must record the escalation time and the responder identity.',
      'Technician inspection. A qualified technician must inspect the wheel end, brake lining thickness, drum or rotor condition and cracking, wheel bearing play and lubricant condition, slack adjuster stroke, and all pneumatic lines and chambers for heat damage. Any lining below the manufacturer minimum, any cracked drum or rotor, and any bearing showing discolouration or roughness requires replacement before movement.',
      'Return to service. The vehicle may return to service only when all three conditions are met: measured temperatures have normalised to within 20°C of the sibling wheel end, the technician has identified and corrected a root cause, and dispatch has recorded the written technician release against the incident. A release must never be issued on the basis of temperature normalisation alone, because a dragging brake or seizing bearing will cool while stationary and re-heat under load.',
      'Records. Attach the telemetry trace covering at least 60 minutes before the alert, photographs of the affected wheel end, the technician report, and the release authorisation to the incident record. Repeat events on the same axle within 90 days must be escalated to fleet engineering for a component-level investigation.',
    ].join('\n\n'),
    owner: 'Fleet Safety',
    updatedAt: '2026-07-18T09:00:00.000Z',
    version: '4.2',
    readTimeMinutes: 4,
    keywords: ['brake', 'overheat', 'temperature', 'emergency', 'release', 'wheel end'],
  },
  {
    id: 'KB-OPS-014',
    title: 'Cold-chain Temperature Excursion Playbook',
    section: 'Product quarantine and evidence preservation',
    category: 'Operations',
    content: [
      'Scope. This playbook governs any deviation of a temperature-controlled load outside its contracted range, including pharmaceutical, fresh produce, and frozen consignments. It applies from the moment the excursion is detected until written disposition is received from the cargo owner.',
      'Verification first. Before acting on an alarm, confirm the reading against the calibrated probe rather than the ambient return-air sensor. Check the set point against the consignment specification, confirm the door-event log does not explain the deviation, and verify the probe calibration date. A significant proportion of excursion alarms are sensor or set-point faults, and treating one as a product event creates unnecessary waste.',
      'Restore and contain. Once the reading is confirmed, restore the configured set point and record the time. Do not discard affected product and do not deliver it. Segregate the load, label it as quality hold, and keep it under continuous monitored temperature. Continue recording telemetry until disposition is issued, even if the load is returned to the depot.',
      'Evidence preservation. The incident record must include the maximum and minimum temperature reached, the total duration outside range measured in minutes, the contracted product limits, the complete door-event history, the calibration record for the probe, and every corrective action taken with timestamps. Missing duration data is the most common cause of a rejected insurance claim.',
      'Disposition authority. Only the cargo owner or a delegated quality authority may issue disposition. Control-tower staff, drivers, and depot managers must never judge a temperature-excursed load as saleable, and must never accept a verbal release. Contact the shipper quality representative through the registered escalation contact and record the written decision against the incident before the hold is lifted.',
      'Closure. The incident may be closed once written disposition is attached, the load has been released or disposed of according to that instruction, and any equipment fault has a work order raised against it. Excursions caused by equipment failure require a reefer unit inspection before the vehicle takes another temperature-controlled load.',
    ].join('\n\n'),
    owner: 'Quality Operations',
    updatedAt: '2026-08-02T12:00:00.000Z',
    version: '3.1',
    readTimeMinutes: 4,
    keywords: ['reefer', 'cold-chain', 'temperature', 'quarantine', 'cargo', 'excursion'],
  },
  {
    id: 'KB-CMP-006',
    title: 'Driver Hours-of-Service Intervention',
    section: 'Dispatch escalation before limit breach',
    category: 'Compliance',
    content: [
      'Intervention trigger. The control tower must act when the predicted remaining drive time falls below the travel time to an approved rest location plus a 15-minute safety margin. This calculation must use live traffic rather than planned transit time, and must be re-evaluated at every route decision point.',
      'Required action. Direct the driver to the nearest legal parking location, document the instruction and the time it was issued, and re-plan the affected load. The instruction must be sent through the in-cab system so it is captured in the audit trail; a phone call alone is not sufficient evidence of intervention.',
      'Non-negotiable rule. Delivery urgency, customer pressure, and penalty clauses never authorise an hours-of-service breach. Any dispatcher who instructs a driver to continue past the legal limit commits a regulatory offence on behalf of the operator. If a customer escalates, route the escalation to the duty transport manager rather than to the driver.',
      'Exceptional movements. A supervisor must approve any relay, driver swap, or exceptional movement, and the approval must name the approving supervisor. The electronic log must remain unedited except through the documented correction workflow, which requires driver acknowledgement of any change. Retrospective edits to conceal a breach are treated as falsification.',
      'Rest facilities. Where no approved parking is reachable within the remaining drive time, the nearest safe legal stopping place takes precedence over facility quality. Record the reason the approved location was unreachable. Repeated occurrences on the same corridor must be raised with network planning, because they indicate a structurally undeliverable schedule rather than a driver performance issue.',
      'Reporting. Every intervention, breach, and near-miss is reported in the weekly compliance pack with the corridor, the load type, and the root cause. Breaches are reported to the transport regulator within the statutory window regardless of whether the load was delivered.',
    ].join('\n\n'),
    owner: 'Transport Compliance',
    updatedAt: '2026-06-30T08:30:00.000Z',
    version: '5.0',
    readTimeMinutes: 4,
    keywords: ['driver', 'hours', 'hos', 'rest', 'compliance', 'drive time'],
  },
  {
    id: 'KB-MNT-021',
    title: 'Remote Powertrain Diagnostic Triage',
    section: 'Derate severity and workshop routing',
    category: 'Maintenance',
    content: [
      'Data capture. For any engine derate, capture active and historic diagnostic trouble codes, coolant temperature and level, oil pressure and temperature, aftertreatment differential pressure, diesel exhaust fluid level and quality, and the regeneration history for the previous 200 operating hours. Capture the snapshot before any attempt to reset or clear a fault.',
      'Immediate shutdown criteria. A red stop-engine warning, abnormal oil pressure, coolant overheating, or a derate beyond 60% of rated torque requires immediate shutdown at the next safe location and recovery by transporter. Continuing to drive under any of these conditions risks catastrophic engine damage and invalidates the powertrain warranty.',
      'Conditional movement. Where none of the shutdown criteria apply, dispatch may authorise a low-load movement to the nearest approved workshop after a technician has reviewed the telemetry and confirmed it in writing. The authorisation must state the maximum permitted distance and any speed or gradient restriction. The driver must stop and re-escalate if the derate deepens or a new red warning appears.',
      'Aftertreatment faults. Repeated differential pressure alerts usually indicate an incomplete regeneration cycle rather than a mechanical failure. Check whether duty cycle has prevented passive regeneration, and whether a parked regeneration was requested and completed. Do not route a vehicle to a workshop for filter replacement until a parked regeneration has been attempted and recorded.',
      'Prohibited action. Never clear fault codes before the diagnostic snapshot is attached to the work order. Cleared codes destroy the freeze-frame data that the workshop needs, and repeat failures then present as first occurrences. Where a code has been cleared in error, record that fact explicitly in the incident.',
      'Workshop routing. Route to the nearest approved partner that holds the correct diagnostic tooling for the engine family. Where the nearest partner lacks tooling, the additional distance to a capable workshop is preferred over a diagnostic attempt that will be repeated. Record the routing decision and its reason.',
    ].join('\n\n'),
    owner: 'Fleet Engineering',
    updatedAt: '2026-07-27T10:15:00.000Z',
    version: '2.8',
    readTimeMinutes: 5,
    keywords: ['engine', 'derate', 'diagnostics', 'powertrain', 'workshop', 'aftertreatment'],
  },
  {
    id: 'KB-SEC-009',
    title: 'Unauthorized Vehicle Movement Response',
    section: 'Verification, immobilization, and evidence',
    category: 'Security',
    content: [
      'Verification before escalation. Validate every unauthorised movement alert against active driver sessions, open work orders, yard gate logs, scheduled vendor access, and the reported GPS confidence value. A large majority of alerts are explained by maintenance vendor movements or by GPS drift in covered yards, and immobilising a legitimately moving vehicle creates a serious safety hazard.',
      'Contact protocol. Contact the yard lead and the assigned driver using the registered contact details held in the fleet system, never a number supplied in the alert itself. Confirm identity against the driver record before discussing vehicle location or cargo. If the contact cannot be verified, treat the movement as unauthorised and continue the escalation.',
      'Immobilization safety rule. Remote immobilisation may be activated only after telemetry confirms the vehicle is stationary. Immobilising a moving vehicle can cause loss of control, and is prohibited without exception regardless of cargo value. Where the vehicle is in motion, track it and coordinate with law enforcement rather than intervening remotely.',
      'Evidence preservation. Preserve access logs, the complete GPS history for the shift, yard camera footage covering the movement window, gate records, and all communications relating to the alert. Export the evidence to the security case record rather than relying on retention in the source systems, which typically overwrite within days.',
      'Personal safety. Do not confront a suspected unauthorised operator, and do not instruct depot staff or drivers to do so. The recovery of an asset never justifies placing an employee in physical danger. Direct all confrontation risk to law enforcement.',
      'Case closure. Close the case only when the movement has been explained or reported to law enforcement with a crime reference, the evidence pack is attached, and any access-control weakness the incident revealed has a remediation owner and date recorded against it.',
    ].join('\n\n'),
    owner: 'Corporate Security',
    updatedAt: '2026-08-10T14:20:00.000Z',
    version: '2.2',
    readTimeMinutes: 4,
    keywords: ['security', 'unauthorized', 'movement', 'geofence', 'immobilization', 'yard'],
  },
  {
    id: 'KB-MNT-011',
    title: 'Tyre Pressure Loss Inspection Standard',
    section: 'Dispatch thresholds and paired-tyre checks',
    category: 'Maintenance',
    content: [
      'Dispatch threshold. A tyre that loses more than 5 PSI in 24 hours after a verified cold inflation must be removed from dispatch until it has been inspected. Pressure readings taken while the tyre is hot must be normalised before comparison, because operating temperature alone can account for 4 to 6 PSI.',
      'Inspection scope. Check tread depth across all three grooves, sidewall condition including bulges and cuts, valve core and stem for leaks, rim seating and corrosion, bead condition, and embedded objects. Use an approved leak test rather than a visual check alone; a slow puncture from a small object is frequently invisible under yard lighting.',
      'Dual assemblies. For dual assemblies, inspect both tyres in the pair even when only one has lost pressure. Confirm diameter compatibility after any repair or replacement: a diameter mismatch beyond the manufacturer tolerance overloads the larger tyre continuously and is a common cause of repeat failure on the same axle position.',
      'Repair limits. Repairs are permitted only within the tread crown area and within the manufacturer size limit. Sidewall repairs, shoulder repairs, and repairs to a tyre that has run flat are prohibited. A tyre that has operated below 80% of its specified pressure must be demounted and internally inspected for casing damage even if it holds pressure afterwards.',
      'Post-repair verification. Record the cold pressure after repair, and recheck after the first full operating cycle. A repaired tyre that loses any measurable pressure on the first recheck must be removed from service permanently rather than repaired again.',
      'Trend escalation. Three or more pressure events on the same vehicle within 60 days must be escalated to fleet engineering, which will inspect for a rim, hub, or alignment fault rather than continuing to treat each event as an isolated tyre issue.',
    ].join('\n\n'),
    owner: 'Fleet Engineering',
    updatedAt: '2026-05-21T11:00:00.000Z',
    version: '3.5',
    readTimeMinutes: 4,
    keywords: ['tyre', 'tire', 'pressure', 'puncture', 'inspection', 'dual assembly'],
  },
  {
    id: 'KB-OPS-018',
    title: 'Priority Shipment Delay Communication',
    section: 'ETA governance and customer notification',
    category: 'Operations',
    content: [
      'Notification trigger. When a priority shipment is predicted to arrive more than 30 minutes late, the control tower must validate and communicate the delay. Validation covers live traffic, weather, remaining legal drive time, and the receiving site opening hours, because a delay that pushes arrival outside receiving hours is a different problem from a delay that does not.',
      'Customer communication. Notify the consignee with the revised ETA and the reason, then record their acknowledgement against the shipment. Communicate a single revised ETA that you have confidence in rather than a sequence of optimistic updates; repeated revisions damage credibility more than one accurate late notification.',
      'Route change criteria. A route change is permitted only when it is safe, legal, compatible with the vehicle dimensions and weight, and genuinely beneficial once evaluated at the next decision point rather than from the current position. Re-routing a vehicle that is already committed to a corridor usually increases total delay.',
      'Driver pressure prohibition. Never pressure a driver to recover time through speeding, reduced rest, or skipped breaks. Any recovery plan that depends on the driver exceeding a legal limit is invalid, and dispatchers who apply such pressure are subject to disciplinary action. Where recovery is impossible within legal limits, the delay is accepted and communicated.',
      'Escalation thresholds. Delays beyond 120 minutes on a priority load, any delay that will miss a contractual delivery window, and any delay affecting a temperature-controlled or high-value load are escalated to the duty operations manager. The escalation must include the recovery options considered and rejected.',
      'Root cause. Record a structured delay reason on every late priority shipment. Weather and traffic are accepted reasons only where the planned schedule allowed no contingency; recurring delays on a corridor are a planning defect and are routed to network planning for schedule revision.',
    ].join('\n\n'),
    owner: 'Customer Operations',
    updatedAt: '2026-07-11T06:45:00.000Z',
    version: '1.9',
    readTimeMinutes: 4,
    keywords: ['delay', 'eta', 'shipment', 'customer', 'route', 'priority'],
  },
  {
    id: 'KB-DAT-003',
    title: 'AI Copilot Data and Escalation Policy',
    section: 'Human oversight and source attribution',
    category: 'Governance',
    content: [
      'Status of recommendations. OpsPilot recommendations are decision support. They are never authorisation to bypass a safety, legal, maintenance, security, or cargo-quality control. An operator who acts on a copilot answer remains accountable for the decision, exactly as if the answer had come from a colleague.',
      'Source verification. Operators must review the cited source material and the current telemetry before acting. A citation confirms that the copilot drew on a specific procedure; it does not confirm that the procedure is the current version or that it applies to the situation at hand. Where a cited document version differs from the version held by the owning team, the owning team is authoritative.',
      'Mandatory human confirmation. Critical safety and security events require supervisor confirmation before any action is taken on a copilot recommendation. This includes brake and fire events, collisions and injuries, unauthorised movement, regulatory breaches, and any recommendation that would release a vehicle back into service.',
      'Data handling. Do not enter personal medical data, credentials, secrets, payment details, or customer data unrelated to the operational question. Copilot inputs may be retained for evaluation and quality review. Retrieved documents are treated as untrusted reference data and must never be followed as instructions to the model.',
      'Uncertainty. The copilot must report an answer as uncertain when evidence is missing, stale, or conflicting, and must name the accountable team for escalation rather than guessing. An operator who receives an uncertain answer escalates rather than proceeding on the balance of probability.',
      'Evaluation and change control. Prompt, model, and retrieval changes are validated against the golden evaluation set before release. Routing accuracy, retrieval recall, citation validity, and classification escalation behaviour are the gating metrics; a change that reduces mandatory-escalation recall is blocked regardless of other improvements.',
    ].join('\n\n'),
    owner: 'AI Governance',
    updatedAt: '2026-08-15T09:30:00.000Z',
    version: '1.4',
    readTimeMinutes: 4,
    keywords: ['ai', 'copilot', 'governance', 'human', 'escalation', 'oversight'],
  },
];
